CREATE TABLE gps
(
    gps_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude   DOUBLE PRECISION,
    longitude  DOUBLE PRECISION,
    altitude   DOUBLE PRECISION,
    speed      DOUBLE PRECISION,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255),
    vehicle_id BIGINT,
    CONSTRAINT pk_gps PRIMARY KEY (gps_id)
);

CREATE TABLE usuario
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255),
    phone      VARCHAR(255),
    role       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuario PRIMARY KEY (user_id)
);

CREATE TABLE vehicle
(
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa      VARCHAR(255),
    marca      VARCHAR(255),
    modelo     VARCHAR(255),
    ano        INTEGER,
    cor        VARCHAR(255),
    tipo       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_vehicle PRIMARY KEY (vehicle_id)
);

ALTER TABLE gps
    ADD CONSTRAINT uc_gps_vehicle UNIQUE (vehicle_id);

ALTER TABLE gps
    ADD CONSTRAINT FK_GPS_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicle (vehicle_id);

ALTER TABLE vehicle
    ADD CONSTRAINT FK_VEHICLE_ON_USER FOREIGN KEY (user_id) REFERENCES usuario (user_id);

INSERT INTO usuario (
    name,
    password,
    email,
    phone,
    role,
    created_at
) VALUES (
    'Thiago Paulo',
    '$2a$10$rTB8bYyHnhMvRUfD1LekmuMlSzadS.p7Wt8BBYxD9W8NBpF91MEo2',
    'utracking@email.com',
    '(84) 99617-1333',
    'ADMIN',
    NOW()
);

INSERT INTO vehicle (
    placa,
    marca,
    modelo,
    ano,
    cor,
    tipo,
    created_at,
    user_id
) VALUES 
(
    'ABC-1234',
    'Volkswagen',
    'Fox',
    2012,
    'Branco',
    'CARRO',
    NOW(),
    1
),
(
    'XYZ-9876',
    'Yamaha',
    'Crosser',
    2015,
    'Branco',
    'MOTOCICLETA',
    NOW(),
    1
);